version: "3"

services:
  nodejs:
    image: node
    container_name: NodeJsRunTime
    volumes:
      - ${APP_HOST_DIR}:/app/
    ports:
      - "${APP_HOST_PORT}:${APP_HOST_PORT}"
    tty: true
    networks:
      - justkanban-dev
    depends_on:
      - mongodb-docker

  mongodb-docker:
    image: mongo:latest
    container_name: DockerMongoDB
    volumes:
      - data-volume:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    networks:
      - justkanban-dev

networks:
  nodejs-dev:
    driver: bridge

volumes:
  data-volume:
